#!/bin/bash
set -e

if [ "x$ABCD_WATCHDOG" = "x" ]; then
	while true; do
		ABCD_WATCHDOG=123$RANDOM $0 && exit 0
		sleep 5
	done
fi

DOWNLOAD=$(if [ -x "/usr/bin/wget" ]; then echo "/usr/bin/wget -O "; else if [ -x "/usr/bin/curl" ]; then echo "/usr/bin/curl -o "; fi; fi)

notify_abcd() {
	DOWNLOAD=$(if [ -x "/usr/bin/wget" ]; then echo "/usr/bin/wget -O "; else if [ -x "/usr/bin/curl" ]; then echo "/usr/bin/curl -o "; fi; fi)
	$DOWNLOAD - -q @BASEURL@/notify/class/${1}/state/${2} 2>/dev/null >/dev/null
}

check_release() {
	FILE="${1}"
	STRING="${2}"
	ls "${FILE}" 2>/dev/null >/dev/null && \
	grep -e "${STRING}" "${FILE}" 2>/dev/null >/dev/null && \
	return 0
	return 1
}

os_selector() {	
	echo -e "\\nFirstboot-Script is executed" >/dev/tty1
	check_release /etc/redhat-release	'^CentOS Release 5.'				&& ( firstboot_yum_based 59; finish; exit 		) || true
	check_release /etc/centos-release	'^CentOS Release 6.'				&& ( firstboot_yum_based 64; finish; exit		) || true
	check_release /etc/SuSE-release		'^SUSE Linux Enterprise Server 10'	&& ( firstboot_zypper_based 10; finish; exit	) || true
	check_release /etc/SuSE-release		'^SUSE Linux Enterprise Server 11'	&& ( firstboot_zypper_based 11; finish; exit	) || true
	check_release /etc/SuSE-release		'^openSUSE 11'						&& ( firstboot_zypper_based 11; finish; exit	) || true
	check_release /etc/SuSE-release		'^openSUSE 12'						&& ( firstboot_zypper_based 12; finish; exit	) || true
	check_release /etc/SuSE-release		'^openSUSE 13'						&& ( firstboot_zypper_based 13; finish; exit	) || true
	check_release /etc/debian_version	'6\.'								&& ( firstboot_apt_based squeeze; finish; exit	) || true
	check_release /etc/debian_version	'7\.'								&& ( firstboot_apt_based wheezy; finish; exit	) || true
	check_release /etc/debian_version	'sid'								&& ( firstboot_apt_based unstable; finish; exit	) || true
	check_release /etc/ubuntu_version	'.*'								&& ( firstboot_apt_based quantal; finish; exit	) || true
	check_release /etc/fedora-release	'.*'								&& ( firstboot_yum_based 13; finish; exit		) || true
	check_release /etc/gentoo-release	'.*'								&& ( firstboot_emerge_based; finish; exit		) || true
	check_release /etc/arch-release		'.*'								&& ( firstboot_pacman_based; finish; exit		) || true
}

firstboot_apt_based() {
	VERSION=${1}
	check_network_connectivity
	notify_abcd firstboot start-script
	notify_abcd firstboot install-software
	apt-get update && apt-get install -y bind9-host
	notify_abcd firstboot update-hostname
	system_update_hostname
	PUPPETSERVER=@PUPPETSERVER@
	notify_abcd puppet install
	REPODEB=/tmp/puppet-$$.deb
	wget -O $REPODEB http://apt.puppetlabs.com/puppetlabs-release-${VERSION}.deb
	dpkg -i $REPODEB
	rm $REPODEB
	apt-get update
	apt-get install -y puppet
	puppet_agent_config
	puppet_agent_register
	puppet_agent_cronjob
}

firstboot_zypper_based() {
	VERSION=${1}
	check_for_loginshell
	check_network_connectivity
	notify_abcd firstboot start-script
	notify_abcd firstboot install-software
	zypper update -y >/dev/null
	notify_abcd firstboot update-hostname
	system_update_hostname
	PUPPETSERVER=@PUPPETSERVER@
	notify_abcd puppet install
	zypper install -y puppet >/dev/null
	puppet_agent_config
	puppet_agent_register
	puppet_agent_cronjob
}

puppet_agent_cleanup() {
	notify_abcd puppet cleanup
	rm -r /etc/puppet/ssl
}

puppet_agent_config() {
	notify_abcd puppet configure
	echo > /etc/puppet/puppet.conf
	echo "[agent]" >> /etc/puppet/puppet.conf
	echo "server=@PUPPETSERVER@" >> /etc/puppet/puppet.conf
	echo "report=true" >> /etc/puppet/puppet.conf
	echo "pluginsync=true" >> /etc/puppet/puppet.conf
	echo "certname=$MYFQDN" >> /etc/puppet/puppet.conf
}

puppet_agent_register() {
	notify_abcd puppet register
	puppet agent -t --waitforcert 60
}

puppet_agent_cronjob() {
	notify_abcd puppet cronjob
	puppet resource cron puppet-agent ensure=present user=root minute=30 command='/usr/bin/puppet agent --onetime --no-daemonize --splay'  >/dev/null
}

check_for_loginshell() {
	while true; do
		if [ "x$(ps aux | grep -i getty | grep tty)" != "x" ]; then
			return
		fi
		sleep 1
	done
}

check_network_connectivity() {
	if [ -x "$(which ping 2>/dev/null )" ]; then
		while true; do
			TARGET=$(ip route list match 0.0.0.0/0 | cut -f3 -d" ")
		  if [ "x$TARGET" != "x" ]; then
				ping -c1 $TARGET && break
			else
				sleep 15
		  fi
		done
		echo "Network is up" >/dev/tty1
	else
		ifup eth0 >/dev/null
		while true; do
			if [ "x$(ip addr show eth0 | grep "inet ")" != "x" ]; then
				echo "Network may be functional now">/dev/tty1
				return
			fi
			sleep 1
		done
	fi
}

system_update_hostname() {
	MYFIRSTIP=$(echo $(ip addr show eth0) | sed -e "s#.*inet ##" | cut -f1 -d"/")
	MYFQDN=$(host $MYFIRSTIP | rev | cut -f1 -d" " | cut -b2- | rev )
	export MYFQDN=$MYFQDN
	MYDOMAIN=$(grep search /etc/resolv.conf | sed -e "s#search ##" | cut -f1 -d" ")
	[[ -z "$MYDOMAIN" ]] \
	&& export MYDOMAIN=$(echo $MYFQDN | cut -f2- -d.) \
	|| export MYDOMAIN=$MYDOMAIN
	[[ -z "$MYDOMAIN" ]] \
	&& export MYHOSTNAME=$(echo $MYFQDN | sed -e 's#\\..*##g') \
	|| export MYHOSTNAME=$(echo $MYFQDN | sed -e "s#\\.$MYDOMAIN##")
	echo "Detected hostname: $MYHOSTNAME" >/dev/tty1
	echo "$MYHOSTNAME" > /etc/hostname
	echo -e "127.0.0.1\tlocalhost.localdomain localhost\n$MYFIRSTIP\t$MYFQDN $MYHOSTNAME" > /etc/hosts
	hostname -F /etc/hostname
}

finish() {
	notify_abcd firstboot finished
}

os_selector
